# Generated by Django 5.2 on 2025-04-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_last_name_alter_user_username_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
    ]
